version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: new_laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - new_laravel_network

    phpmyadmin:
        image: phpmyadmin
        container_name: new_phpmyadmin
        restart: always
        ports:
            - 9090:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - new_laravel_network
    webserver:
        image: nginx:latest
        container_name: new_laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www:delegated
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - new_laravel_network

    db:
        image: mysql:8.0
        container_name: new_laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: new_laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - new_laravel_network

volumes:
    dbdata:

networks:
    new_laravel_network:
        driver: bridge
